name: record

packages:
  - record
  - record/example
  - record_android
  - record_darwin
  - record_linux
  - record_platform_interface
  - record_web
  - record_windows

# Don't generate intellij files
ide:
  intellij: false