name: record_android
description: Android specific implementation for record package called by record_platform_interface.
version: 1.0.4
homepage: https://github.com/llfbandit/record/tree/master/record_android

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^1.0.2

flutter:
  plugin:
    implements: record
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
