name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 1.0.2
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^1.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  plugin:
    implements: record
    platforms:
      windows:
        pluginClass: RecordWindowsPluginCApi
